### PR TITLE
added include and exclude.

### PR DESCRIPTION
**Pull request by gknisely**
@meghanhade Can you add a sentence or two for Mobility Explorer for the following section on how to obtain Onestop IDs?
@irees Can you add a sentence or two for Transitland for the following section on how to obtain Onestop IDs?

Thanks.

### CODE REVIEW

**Comment by irees** [comment]
```
<li>Transitland - The Transitland API can be used to directly query for stops, routes, and operators using a number of options. For example, [subway routes](http://transit.land/api/v1/routes?vehicle_type=metro). Please see the [Transitland Datastore API documentation](https://transit.land/documentation/datastore/api-endpoints.html) for more details.</li>
```

**Comment by meghanhade** [comment]
<li>[Mobility Explorer](https://mapzen.com/mobility/explorer/) - Onestop IDs can be obtained by selecting a single route, stop, or operator by clicking on it on the map. For routes and operators, you may also select by choosing from the drop-down menu in the sidebar. The Onestop ID will then be provided in the sidebar, along with other detailed information about the route, stop or operator you have chosen. More information can be found in the [Mobility Explorer documentation](https://mapzen.com/documentation/mobility/explorer/overview/).</li>

**Comment by gknisely** [comment]
added updates from @irees and @meghanhade   Thank you!

@rmglennon @drewda @dnesbitt61 please review.

**Comment by gknisely** [comment]
Added HOV costing

**Comment by drewda** [comment]
@gknisely This looks good. My one recommendation would be to link the first reference of "Onestop ID" to https://transit.land/documentation/onestop-id-scheme/ for background information.

**Comment by dnesbitt61** [comment]
:shipit:

**Comment by gknisely** [comment]
@drewda thanks and updated.

**Comment by gknisely** [comment]
This is get merge when blog goes out.

**Comment by drewda** [comment]
@gknisely 👍

**Comment by rmglennon** [comment]
I've pushed some changes into this branch for include/exclude. 

Summary:
- removed API keys section and replaced it with a link (to match the trend these days and make the topic less service-oriented)
- replaced sample queries with working links that use keyless access (to match the styling used in the Search docs). This partially resolves #138. 
- moved the sample include/exclude query and Onestop ID info into a new section (the table was cut off or required scrolling otherwise)
- spelled out HOV on first use
- added a sentence on include/exclude to Mobility Explorer isochrone topic...although I'd like to get a demo so I can better understand the behavior.

**Comment by rmglennon** [comment]
Preview links: https://precog.mapzen.com/mapzen/mapzen-docs-generator/rhonda/in-ex-transit/documentation/mobility/turn-by-turn/api-reference/

https://precog.mapzen.com/mapzen/mapzen-docs-generator/rhonda/in-ex-transit/documentation/mobility/explorer/isochrones/

Also, I think the isochrone docs is OK as is because it says you can use the Turn-by-Turn costing for multimodal without repeating the options again in that topic. Let me know if we do need to add something here:

https://mapzen.com/documentation/mobility/isochrone/api-reference/#costing-parameters

**Comment by gknisely** [comment]
Updates look good, but do you think the transition from the Transit costing options table to the "For example, this is a route favoring buses, but also this person walks at a slower speed (4.1km/h):" and back to the new Filter transit data section bouncing around too much?  Maybe move the example below the new Filter transit data section.  Idk not sure.  @rmglennon what do you think?

**Comment by gknisely** [comment]
:shipit: looks good

**Comment by rmglennon** [comment]
Thanks @gknisely. The table loses scroll ability in the table, so my other thought was a separate section with all transit examples. The links look good in GitHub-flavored markdown, but not on the formatted docs site (yet).

**Comment by rmglennon** [comment]
All right, I ended up using HTML and escape characters for the include/exclude example. I also grouped all the transit examples together. 

And put in https://github.com/mapzen/mapzen-docs-generator/issues/242 to look into the link markdown parsing.

**Comment by gknisely** [comment]
:shipit:

**Pull request merged**
