### PR TITLE
Remove mapzen references

### PR DESCRIPTION
**Pull request by dnesbitt61**
Add small section on how to get a Mapbox access_token. Next pass will add sample Mapbox URLs (replaces TBDs).

### CODE REVIEW

**Comment by gknisely** [comment]
:ship:

**Comment by dnesbitt61** [comment]
Pass #1. A second edit is planned, especially around filling in sample URLs.

**Comment by chrislukic** [comment]
I'm trying to find the endpoint for the hosted Mapbox elevation API referenced here.  I can find no reference to it on Mapbox's site, or here. Perhaps these Mapbox hosted endpoints could be added to the docs?

https://api.mapbox.com/{endpoint}?access_token=

**Comment by kevinkreiser** [comment]
@chrislukic right now the APIs are not promoted on the Mapbox site. if you are interested in using the API please contact the Mapbox sales team and they will be able to get you the endpoint

**Comment by chrislukic** [comment]
Ok. Understood.

I've (surprisingly) had no response so far from the message I sent to sales last week, but will continue to try...

**Comment by kevinkreiser** [comment]
@chrislukic apologies for that perhaps i can nudge someone from this end.

**Pull request merged**
