### PR TITLE
Edited to match lrm-mapzen-1.0.0 updates

### PR DESCRIPTION
**Pull request by kdiluca**

### CODE REVIEW

**Comment by rmglennon** [comment]
Thanks! 

I have a few more things to review...let me test this all the way through again.

- LRM is now on a CDN, so I suggest we simplify that part by linking to the reference. Also, I thought we put LRM-Mapzen up there...I can't remember where that stands.
- I recall a reason to use a specific version number in the tangram JS, so I'll have to go back through my notes with the Tangram folks.

**Comment by kdiluca** [comment]
Ok, thanks Rhonda!  I wasn't sure about the tangram url other than it pulls the latest.

**Comment by rmglennon** [comment]
Ah, here was the note about Tangram: https://github.com/valhalla/valhalla-docs/issues/45#issuecomment-166508151

**Comment by rmglennon** [comment]
This should be working now! lrm-mapzen is available through npm, but that also acts as a CDN with a URL, like https://npmcdn.com/lrm-mapzen/dist/lrm-mapzen.js. The tutorial steps are much easier...although does require us to update the version numbers periodically.

(Side note, Tangram does require the local server, so I'll look to simplify those steps in the future.)

**Comment by rmglennon** [comment]
Thanks again @kdiluca for the edits.

**Comment by kdiluca** [comment]
:+1:

**Pull request merged**
