### PR TITLE
Clarify which costing methods can use isochrone date_time parameters

### PR DESCRIPTION
**Pull request by rmglennon**
You might expect either real-time traffic or some historic/estimated traffic information and wonder why the isochrones look the same for vehicle travel when you have set a date and a time. This states which parameters are available for which costing methods. 

@kevinkreiser, please review and make sure I updated these correctly!

### CODE REVIEW

**Comment by gknisely** [comment]
This is incorrect.  The previous description was accurate.  Date and time can be used for all costing methods.  However, arrive_by will not work for multimodal.

**Comment by gknisely** [comment]
Unless the isochrone logic is different from the routing logic.

**Comment by kevinkreiser** [comment]
no arrive by regardless of mode: https://github.com/valhalla/valhalla/blob/master/src/loki/isochrone_action.cc#L65

only multimodal tracks the time during expansion: https://github.com/valhalla/valhalla/blob/master/src/thor/isochrone.cc#L416

**Comment by gknisely** [comment]
Maybe we should error on it if they send in a date_time for non-multimodal?  Otherwise, they may expect it to do something different.  Thoughts?

**Comment by dnesbitt61** [comment]
I don't think so. Add something like Kevin says - for isochrones date time currently only impacts multimodal

**Comment by rmglennon** [comment]
OK, I've updated this to indicate that date_time is only for multimodal. @kevinkreiser and I were chatting about this, but he was talking about arrive by working for vehicles in routing when I thought isochrones.

**Comment by dnesbitt61** [comment]
:shipit:

**Pull request merged**
